Delete ShooterTriggerChangeUi,GimbalTriggerChangeUi,and add EventTriggerChangeUi.
chenhuiYu00/rm_control pull request #1
Opened 2023-04-18 13:52 UTC by YoujianWu

Delete ShooterTriggerChangeUi,GimbalTriggerChangeUi,and add EventTriggerChangeUi.

2023-04-18 14:49 UTC, chenhuiYu00 requested changes

2023-04-18 14:49 UTC, chenHurry00 commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +  void updateManualCmdData(const rm_msgs::ManualToReferee::ConstPtr data, const std::string& event);
更新部分的函数不用具体到某个话题的函数，只需要一个 updateXXXXStateData的函数即可，参数不用传整个msg，传入关键的某个标志的值

2023-04-18 14:49 UTC, chenHurry00 commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +  virtual void display(const std::string& event);
不要增加不必要的display函数

2023-04-18 14:49 UTC, chenhuiYu00 commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +                            bool sub_flag = false){};
updateConfig函数也不要重载，这是一个通用函数

2023-04-18 14:49 UTC, chenhuiYu00 commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +                            bool sub_flag = false){};
你已经有event成员变量了，不用传进去，直接用它即可

2023-04-18 15:41 UTC, chenhuiYu00 commented on rm_referee/include/rm_referee/ui/trigger_change_ui.h
> +                            bool sub_flag = false){};
> 我一直没有注意到我还有一个event成员变量可以用，我再重新修改一下。 还有一个问题，if语句能用switch case语句代替吗？

可以，不过由于我们代码规范的原因，case语句的break什么的会单独作为一行存在而占用空间，如果代码最后不太美观就用回if

2023-04-19 10:20 UTC, YoujianWu commented
删除了原来增加的display函数和updateconfig函数，更新部分的函数改为了一个 updateEventStateData的函数，参数传了对应msg里的state，并用成员变量event_替代了函数传入字符串参数，并修改了编译时报的错，现在成功编译了。现在看看怎么样？ @chenhuiYu00

2023-04-25 12:24 UTC, chenhuiYu00 commented
> 删除了原来增加的display函数和updateconfig函数，更新部分的函数改为了一个 updateEventStateData的函数，参数传了对应msg里的state，并用成员变量event_替代了函数传入字符串参数，并修改了编译时报的错，现在成功编译了。现在看看怎么样？ @chenhuiYu00



> 删除了原来增加的display函数和updateconfig函数，更新部分的函数改为了一个 updateEventStateData的函数，参数传了对应msg里的state，并用成员变量event_替代了函数传入字符串参数，并修改了编译时报的错，现在成功编译了。现在看看怎么样？ @chenhuiYu00

当你完成了我的一个意见后，点击reslove conversation按钮，这样我就会收到解决的信息。除非他忘了看，尽量不要直接@人，relove意见后我们有时间就会看。

2023-04-25 12:26 UTC, chenhuiYu00 commented
> 删除了原来增加的display函数和updateconfig函数，更新部分的函数改为了一个 updateEventStateData的函数，参数传了对应msg里的state，并用成员变量event_替代了函数传入字符串参数，并修改了编译时报的错，现在成功编译了。现在看看怎么样？ @chenhuiYu00

现在试着我说的去做，把上面的review reslove掉，注意点那个按钮前确保问题已经解决，如果对建议不认同就提出反馈

2023-07-07 11:19 UTC, closed without merging